version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "America/New_York"
    reviewers:
      - "junapur"
    assignees:
      - "junapur"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "12:00"
      timezone: "America/New_York"
    reviewers:
      - "junapur"
    assignees:
      - "junapur"
