name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Spotted a bug?** 🐞
        Let us know what went wrong so we can fix it.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "Example: When I try to do X, my computer explodes. This definitely should not happen."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: What are the steps we can take to reproduce this bug?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: "Example: 1.0.0"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm you've completed these steps.
      options:
        - label: I've searched the issue tracker and confirmed this isn't a duplicate.
          required: true
