name: Feature Request
description: "Have an idea for a new feature? Let us know!"
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for helping us improve!** 🎉
        Just a few details from you will help us understand your idea better.

  - type: textarea
    id: details
    attributes:
      label: Feature Details
      description: What you'd like added, the benefits it brings, and any design or UX considerations.
      placeholder: "Example: A dark mode toggle to reduce eye strain at night; ideally located in Settings beside the theme options."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm you've completed these steps.
      options:
        - label: I've searched the issue tracker and confirmed this isn't a duplicate.
          required: true
